language: android

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android

android:
  components:
    - build-tools-20.0.0
    - android-10
  licenses:
    - android-sdk-license-5be876d5

env:
  global:
  - secure: "N65Gr043MKcOCsRGTaG4Agk+MxTV/QXUU753Z7jgLqaz6oGugtb25oh7fuQ5OrSuF/XV2AXJaM03++2Wa3Xadp4CCA/ciJUMFhmy5KY/PLzpnNtFO0HY0B1IPS79fvsLKNnMaQTW46hnQWIvsXCfTjqzXIZ612ZcQxFdYZEUpns="
  - secure: "W6QGZAbSdKkLJQ53hDs5LXRNNCQnv18W40/h2vkEdoImIJ3pZX/gTbycmS0D3x7Ev8BsgjH0/jaK+BeTRmABBs2U7jld7XN690O3dkHTSONRVcRk9litCpvBDnzlt6EaMjvYZSzJ4YPBefG1MFtw+dJkZ5sO6k1J81zaOAXSI90="

install:
- TERM=dumb ./gradlew -q -s clean assemble

script:
- TERM=dumb ./gradlew -s --continue check install integrationTests

after_success:
- ./scripts/deploy_to_maven.sh
